=== IngSoftware3CM2/proyecto/PLANTILLACSS/expo/DataBase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="database">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="user" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="username" type="xs:string"/>
							<xs:element name="password" type="xs:string"/>
							<xs:element name="firstname" type="xs:string"/>
							<xs:element name="lastname" type="xs:string"/>
							<xs:element name="email" type="xs:string"/>
							<xs:element name="occupation">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="student|teacher|administrator"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="classroom" type="xs:string" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="groups">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="class" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
                                <xs:element name="file" maxOccurs="unbounded" minOccurs="0">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="filename" type="xs:string" />
                                            <xs:element name="group" type="xs:string" />
                                            <xs:element name="comments">
                                                <xs:complexType>
                                                <xs:sequence>
                                                <xs:element name="bodycom" type="xs:string" />
                                                <xs:element name="grade" default="-" />
                                                </xs:sequence>
                                                <xs:attribute name="username" type="xs:string" use="required"></xs:attribute>     
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== IngSoftware3CM2/proyecto/PLANTILLACSS/expo/dataBase.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DataBase.xsd">
  <user>
    <username>bennett2idea</username>
    <password>1234</password>
    <firstname>Angie</firstname>
    <lastname>Bennett</lastname>
    <email>bennett2idea@gmail.com</email>
    <occupation>teacher</occupation>
    <classroom>1</classroom>
  </user>
  <user>
    <username>francisbell959</username>
    <password>cKrZrUHp</password>
    <firstname>Francis</firstname>
    <lastname>Bell</lastname>
    <email>francisbell959@gmail.com</email>
    <occupation>teacher</occupation>
    <classroom>2CM5</classroom>
  </user>
  <user>
    <username>hampton2wealth</username>
    <password>nMWkir3J</password>
    <firstname>Tracy</firstname>
    <lastname>Hampton</lastname>
    <email>hampton2wealth@gmail.com</email>
    <occupation>student</occupation>
    <classroom>2CM10</classroom>
  </user>
  <user>
    <username>goodman832sign</username>
    <password>KY5nVjY4</password>
    <firstname>Candice</firstname>
    <lastname>Goodman</lastname>
    <email>goodman832sign@gmail.com</email>
    <occupation>student</occupation>
    <classroom>1</classroom>
  </user>
  <user>
    <username>nicholas110heat</username>
    <password>C6y461XM</password>
    <firstname>Nicholas</firstname>
    <lastname>Osborne</lastname>
    <email>nicholas110heat@gmail.com</email>
    <occupation>student</occupation>
    <classroom>1</classroom>
  </user>
  <user>
    <username>mindy73sink</username>
    <password>lNbi9uJb</password>
    <firstname>Mindy</firstname>
    <lastname>Walton</lastname>
    <email>mindy73sink@gmail.com</email>
    <occupation>student</occupation>
    <classroom>1</classroom>
  </user>
  <user>
    <username>fox51spiders</username>
    <password>ZY55l1ok</password>
    <firstname>Vicky</firstname>
    <lastname>Fox</lastname>
    <email>fox51spiders@gmail.com</email>
    <occupation>student</occupation>
    <classroom>1</classroom>
  </user>
  <user>
    <username>noah9screw</username>
    <password>7AUiS4MB</password>
    <firstname>Noah</firstname>
    <lastname>Park</lastname>
    <email>noah9screw@gmail.com</email>
    <occupation>student</occupation>
    <classroom>1</classroom>
  </user>
  <user>
    <username>hunter9calculator</username>
    <password>IeYNikNH</password>
    <firstname>Cora</firstname>
    <lastname>Hunter</lastname>
    <email>hunter9calculator@gmail.com</email>
    <occupation>student</occupation>
    <classroom>1</classroom>
  </user>
  <user>
    <username>curtis3sink</username>
    <password>ZMxmtgO0</password>
    <firstname>Marta</firstname>
    <lastname>Curtis</lastname>
    <email>curtis3sink@gmail.com</email>
    <occupation>student</occupation>
    <classroom>1</classroom>
  </user>
  <user>
    <username>abdc</username>
    <password>123</password>
    <firstname>Dante</firstname>
    <lastname>Curtis</lastname>
    <email>abdcD@gmail.com</email>
    <occupation>student</occupation>
    <classroom>1</classroom>
  </user>
  <user>
    <username>arcoiris</username>
    <password>iris</password>
    <firstname>leticia</firstname>
    <lastname>angeles</lastname>
    <email>letitia_russell_angels@hotmail.com</email>
    <occupation>administrator</occupation>
  </user>
  <groups>
    <class>2CM10</class>
    <class>2CM5</class>
    <class>2CM2</class>
  </groups>
  
</database>
